name: SSH deploy on push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn

      - name: Build project
        run: yarn build

      - name: Deploy to remote server
        uses: burnett01/rsync-deployments@5.2.1
        with:
          switches: -avzr --delete
          path: ./build/
          remote_host: ${{ secrets.REMOTE_HOST }}
          remote_key: ${{ secrets.REMOTE_KEY }}
          remote_user: ${{ secrets.REMOTE_USER }}
          remote_path: ${{ secrets.REMOTE_PATH }}